"""
Core data types for the TradingAgents replica framework.

This module defines the standardized data structures that represent the state
and communication between agents across all three approaches (Perplexity API,
weak LLM, and quant-only). By using immutable, structured types, we avoid the
"telephone effect" and ensure reproducibility and comparability.

Reference: TradingAgents paper emphasizes structured communication between agents
to maintain information fidelity across the multi-agent pipeline.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from datetime import date


@dataclass
class MarketContext:
    """
    Represents the complete observable market state for a single ticker on a given day.

    This is the primary input to all agents. It encapsulates:
    - Price and volume data (from yfinance)
    - Pre-computed technical indicators (MACD, RSI, MAs, Bollinger Bands, etc.)
    - Fundamental ratios (P/E, P/B, ROE, etc.) if available
    - Sentiment scores from news/social (if approach supports it)
    - Current portfolio state (position size, cash, risk limits)

    Attributes:
        symbol (str): Ticker symbol, e.g., "AAPL"
        as_of (date): Decision date. All data is as-of EOD this date (no look-ahead).

        -- Price & Volume (daily OHLCV) --
        open (float): Opening price
        high (float): Highest price of the day
        low (float): Lowest price of the day
        close (float): Closing price (commonly used as reference)
        adj_close (float): Adjusted close (accounts for stock splits, dividends)
        volume (float): Number of shares traded

        -- Technical Indicators (pre-computed by data_loader.py) --
        technicals (Dict[str, float]): Keys: "MACD", "RSI", "BB_upper", "BB_lower", etc.
            Example: {"MACD": 0.15, "RSI": 65.0, "SMA_20": 150.2, "SMA_50": 149.8}
            Interpretation: standardized 0-100 scale where applicable

        -- Fundamental Metrics --
        fundamentals (Dict[str, float]): Keys: "PE_ratio", "PB_ratio", "ROE", etc.
            Example: {"PE_ratio": 25.3, "PB_ratio": 2.1, "ROE": 0.18}
            Note: May be empty or sparse depending on data availability

        -- Sentiment & Alternative Data --
        sentiment_scores (Dict[str, float]): Aggregated sentiment signals (-1 to +1 range)
            Example: {"news_sentiment": 0.2, "social_sentiment": -0.1, "insider_score": 0.05}
            Note: Empty dict in quant-only approach; populated by LLM-based approaches

        -- Portfolio State --
        current_position (float): Current number of shares held (can be 0 or negative if short)
        cash (float): Available cash in portfolio
        portfolio_value (float): Total portfolio value (positions + cash)
        risk_limits (Dict[str, Any]): Risk constraints applied by RiskManager
            Example: {"max_position_pct": 0.2, "max_drawdown_pct": 0.05, "max_leverage": 1.5}

        -- Extensibility --
        extra (Optional[Dict[str, Any]]): Approach-specific data
            Used by individual approaches to attach custom metadata without polluting core types
    """

    symbol: str
    as_of: date

    # Price and volume
    open: float
    high: float
    low: float
    close: float
    adj_close: float
    volume: float

    # Pre-computed technical indicators (calculated by data_loader)
    technicals: Dict[str, float]

    # Fundamental metrics (P/E, P/B, ROE, etc.)
    fundamentals: Dict[str, float]

    # Sentiment and alternative data signals (empty in quant-only approach)
    sentiment_scores: Dict[str, float]

    # Current portfolio state
    current_position: float
    cash: float
    portfolio_value: float
    risk_limits: Dict[str, Any]

    # Approach-specific extensions
    extra: Optional[Dict[str, Any]] = None


@dataclass
class AnalystReport:
    """
    Output of a single specialist analyst (Fundamental, Technical, News, Sentiment).

    Each analyst receives MarketContext and produces a structured report with:
    - Standardized numerical signals for downstream agents
    - Risk flags/warnings
    - Human-readable summary (generated by LLM or template)
    - Confidence score

    This avoids long chains of natural language and maintains information clarity,
    a key design principle in the TradingAgents paper.

    Attributes:
        symbol (str): Ticker being analyzed
        as_of (date): Analysis date (same as MarketContext.as_of)
        analyst_type (str): Type of analysis: "fundamental", "technical", "news", or "sentiment"

        signals (Dict[str, float]): Standardized numerical signals for this analyst
            - Range: typically 0-1 (higher = more bullish) or -1 to +1
            - Keys depend on analyst_type:
              * fundamental: {"value_score": 0.7, "quality_score": 0.8, "growth_score": 0.5}
              * technical: {"momentum_score": 0.6, "trend_score": 0.8, "overbought_flag": 0.0}
              * news: {"positive_events": 2, "negative_events": 0, "net_sentiment": 0.8}
              * sentiment: {"social_sentiment": 0.2, "insider_score": 0.05}

        risk_flags (List[str]): Warning flags for the trader/risk team
            Example: ["high_valuation", "earnings_coming_soon", "high_volatility"]

        summary (str): Human-readable narrative of the analysis (generated by LLM or template)
            Example: "High P/E ratio (30x) relative to sector average (25x) suggests valuation stretched.
                      However, 15% YoY revenue growth and positive earnings revisions support quality."

        confidence (float): Analyst's confidence in this assessment (0-1 range)
            Example: 0.85 means analyst is quite confident, but leaves room for uncertainty

        extra (Dict[str, Any]): Additional metadata (e.g., feature importance, data sources)
    """

    symbol: str
    as_of: date
    analyst_type: str  # "fundamental", "technical", "news", or "sentiment"

    # Standardized numerical signals (0-1 or -1 to +1, depending on signal type)
    signals: Dict[str, float]

    # Risk/warning flags specific to this analyst's domain
    risk_flags: List[str]

    # Natural language summary (generated by LLM in LLM approaches, by template in quant)
    summary: str

    # Subjective confidence in this analysis (0-1)
    confidence: float

    # Extensible metadata
    extra: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ResearchReport:
    """
    Output of the Research Team (Bullish & Bearish researchers in debate).

    This stage aggregates the four AnalystReports into a unified bull/bear stance.
    In LLM approaches, this involves multi-turn dialogue between agents.
    In quant-only, this is a weighted combination of analyst signals.

    The key insight from TradingAgents: structured debate produces better decisions than
    single-agent reasoning, especially when time-horizons are complex.

    Attributes:
        symbol (str): Ticker under research
        as_of (date): Research date

        stance_score (float): Aggregate bull/bear sentiment (-1 to +1)
            -1 = strongly bearish, 0 = neutral, +1 = strongly bullish
            Typically computed as: (bullish_evidence - bearish_evidence) / normalization

        bullish_summary (str): Bull researcher's case (why to buy or hold)
            Example: "Strong fundamentals, positive technicals (MACD>0, RSI<70), 
                      recent insider buying signals confidence."

        bearish_summary (str): Bear researcher's case (why to sell or avoid)
            Example: "Valuation stretched (30x P/E), earnings guidance conservative,
                      sector headwinds (rising rates)."

        dominant_view (str): Which view "won" the debate: "bullish", "bearish", or "neutral"
            Used by Trader to break ties or weight the decision

        confidence (float): Global confidence in this research (0-1)
            Lower if debate was close; higher if one side dominated

        supporting_analysts (Dict[str, Any]): Metadata on which analysts contributed
            Example: {"fundamental_contribution": 0.8, "technical_contribution": 0.6}

        extra (Optional[Dict[str, Any]]): Debate history, reasoning trace, etc. (optional)
    """

    symbol: str
    as_of: date

    # Aggregate stance: >0 = bullish, <0 = bearish, ~0 = neutral
    stance_score: float

    # Bullish researcher's narrative
    bullish_summary: str

    # Bearish researcher's narrative
    bearish_summary: str

    # Which perspective prevailed in the debate
    dominant_view: str  # "bullish", "bearish", or "neutral"

    # Confidence in the overall research conclusion
    confidence: float

    # References to which analysts influenced this research
    supporting_analysts: Dict[str, Any]

    # Optional: debate history, reasoning trace, or approach-specific details
    extra: Optional[Dict[str, Any]] = None


@dataclass
class Decision:
    """
    Final trading decision output by the Trader agent, reviewed/modified by Risk & Fund Manager.

    This is the action executed in the backtest: buy/sell/hold, how many shares, with what risk controls.

    Attributes:
        symbol (str): Ticker being traded
        as_of (date): Decision date

        action (str): Trading action
            Values: "buy", "sell", "hold" (can extend to "short", "cover", etc.)

        target_position (float): Desired number of shares to hold after this trade
            Example: 100 means end up with 100 shares; if currently holding 50, trade_size = 50

        trade_size (float): Delta in shares (positive = buy, negative = sell, zero = hold)
            Automatically computed: trade_size = target_position - current_position

        reference_price (float): Price used for this decision (typically close price of as_of date)
            Serves as documentation and for slippage analysis

        rationale (str): Concise justification (for logs, explainability, and audit trail)
            Example: "Bullish research + oversold RSI = entry opportunity; 2% stop-loss below entry"

        confidence (float): Confidence in this decision (0-1)
            Example: 0.75 means trader is fairly confident but with room for uncertainty

        risk_overrides (Dict[str, Any]): Risk constraints/controls applied by Risk Manager
            Example: {
                "max_loss_pct": 0.03,        # max loss is 3% of current position value
                "take_profit_pct": 0.08,    # exit at 8% gain
                "position_size_limit": 50,  # do not exceed 50 shares
                "stop_loss_price": 148.5    # hard stop at this price
            }

        metadata (Dict[str, Any]): Pipeline metadata for analysis/debugging
            Example: {
                "approach": "llm_perplexity",
                "policy_version": "v1",
                "research_stance": "bullish",
                "risk_profile": "neutral"
            }
    """

    symbol: str
    as_of: date

    # Trading action
    action: str  # "buy", "sell", "hold"

    # Target position and trade delta
    target_position: float
    trade_size: float

    # Reference price for this decision
    reference_price: float

    # Justification and confidence
    rationale: str
    confidence: float

    # Risk management constraints (set or modified by RiskManager)
    risk_overrides: Dict[str, Any]

    # Metadata for reproducibility and analysis
    metadata: Dict[str, Any]


@dataclass
class AgentState:
    """
    Aggregated state of all agents during a single day's decision cycle.

    This captures the complete flow of information from market context through
    all agents (analysts -> researchers -> trader -> risk -> fund manager -> decision).
    Serves as both internal state and audit trail for each day.

    Attributes:
        symbol (str): Ticker being decided on
        as_of (date): Decision date

        market_context (MarketContext): Raw market data and portfolio state

        analyst_reports (List[AnalystReport]): Reports from all four analysts
            Order: [fundamental, technical, news, sentiment] for consistency

        research_report (Optional[ResearchReport]): Aggregated bull/bear research
            None if approach skips research stage (rare)

        final_decision (Optional[Decision]): Final decision after risk review
            None if decision has not yet been made (in-progress state)

        timestamps (Dict[str, Any]): Timing metadata for performance analysis
            Example: {"analysis_start": 10:00, "research_start": 10:05, "decision_time": 10:10}

        logs (List[str]): Debug/audit logs during the day's processing
            Example: ["Fundamental analyst bullish (+0.7)", "Technical analyst neutral (-0.05)"]
    """

    symbol: str
    as_of: date

    # Input: market data
    market_context: MarketContext

    # Stage 1: Analyst reports
    analyst_reports: List[AnalystReport]

    # Stage 2: Research aggregation
    research_report: Optional[ResearchReport] = None

    # Stage 3: Final decision (after risk review)
    final_decision: Optional[Decision] = None

    # Metadata: timing and logs
    timestamps: Dict[str, Any] = field(default_factory=dict)
    logs: List[str] = field(default_factory=list)


@dataclass
class BacktestResult:
    """
    Aggregated result of a complete backtest run for one or more tickers.

    Captures performance metrics (CR, AR, Sharpe, MDD), trade history, and metadata.
    Used for comparison between approaches and against baselines.

    Attributes:
        symbol (str): Ticker(s) backtested (e.g., "AAPL" or "AAPL,NVDA,MSFT")
        start_date (date): Backtest start date
        end_date (date): Backtest end date

        -- Performance Metrics (definition: see metrics.py) --
        cumulative_return (float): Total return as % (e.g., 0.25 = 25%)
        annualized_return (float): Annualized return as % (e.g., 0.08 = 8% annual)
        sharpe_ratio (float): Risk-adjusted return (higher is better, >1.0 is good)
        max_drawdown (float): Maximum loss from peak as % (negative, e.g., -0.15 = -15%)

        -- Trade Details --
        num_trades (int): Total number of buy/sell actions executed
        num_winning_trades (int): Trades that closed at a profit
        win_rate (float): Percentage of winning trades (0-1)

        -- Account Summary --
        initial_capital (float): Starting portfolio value
        final_value (float): Ending portfolio value

        -- Metadata --
        approach (str): Which approach used: "llm_perplexity", "llm_weak", "quant_only", "baseline_macd", etc.
        strategy_name (str): Human name for the strategy
        metadata (Dict[str, Any]): Extra config, hyperparameters, notes
    """

    symbol: str
    start_date: date
    end_date: date

    # Performance metrics
    cumulative_return: float
    annualized_return: float
    sharpe_ratio: float
    max_drawdown: float

    # Trade counts
    num_trades: int
    num_winning_trades: int
    win_rate: float

    # Account summary
    initial_capital: float
    final_value: float

    # Metadata
    approach: str
    strategy_name: str
    metadata: Dict[str, Any] = field(default_factory=dict)